[SDG0]
nombre=
valorGrupo=0
valorDecimal=1
valorHexadecimal=1
valorBinario=1
nombresBits=D0-D1-D2-D3-D4-D5-D6-D7
entradaBits=-------
estadoEntradaBits=0-0-0-0-0-0-0-0
secuencia=0
ordenSecuencia=0
valorInicio=0
valorFin=255
tiempoSecunecia=0
duracion=0
diferencial=0-0-0-0
frecuencias=0-0-0-0
conmutaBits=0-0-0-0-0-0-0-0
frecuBits=0-0-0-0-0-0-0-0

[SDG1]
nombre=
valorGrupo=0
valorDecimal=1
valorHexadecimal=1
valorBinario=1
nombresBits=D8-D9-D10-D11-D12-D13-D14-D15
entradaBits=-------
estadoEntradaBits=0-0-0-0-0-0-0-0
secuencia=0
ordenSecuencia=0
valorInicio=0
valorFin=255
tiempoSecunecia=0
duracion=0
diferencial=0-0-0-0
frecuencias=0-0-0-0
conmutaBits=0-0-0-0-0-0-0-0
frecuBits=0-0-0-0-0-0-0-0

[SDG2]
nombre=COMPARADOR D19
valorGrupo=31
valorDecimal=1
valorHexadecimal=1
valorBinario=1
nombresBits=A8-A9-A10-A11-A12-A13-A14-A15
entradaBits=-------
estadoEntradaBits=0-0-0-0-0-0-0-0
secuencia=0
ordenSecuencia=0
valorInicio=0
valorFin=255
tiempoSecunecia=0
duracion=0
diferencial=0-0-0-0
frecuencias=0-0-0-0
conmutaBits=0-0-0-0-0-0-0-0
frecuBits=0-0-0-0-0-0-0-0

[SDG3]
nombre=
valorGrupo=70
valorDecimal=1
valorHexadecimal=1
valorBinario=1
nombresBits=SEL1-SEL0-CS_0-A7-ED4-SEL2-A0-A1
entradaBits=-------
estadoEntradaBits=0-0-0-0-0-0-0-0
secuencia=0
ordenSecuencia=0
valorInicio=0
valorFin=255
tiempoSecunecia=0
duracion=0
diferencial=0-0-0-0
frecuencias=0-0-0-0
conmutaBits=0-0-0-0-0-0-0-0
frecuBits=0-0-0-0-0-0-0-0

[SDG4]
nombre=
valorGrupo=250
valorDecimal=1
valorHexadecimal=1
valorBinario=1
nombresBits=A2-A3-A4-A5-A6-R-W-IO_0
entradaBits=-------
estadoEntradaBits=0-0-0-0-0-0-0-0
secuencia=0
ordenSecuencia=0
valorInicio=0
valorFin=255
tiempoSecunecia=0
duracion=0
diferencial=0-0-0-0
frecuencias=0-0-0-0
conmutaBits=0-0-0-0-0-0-0-0
frecuBits=0-0-0-0-0-0-0-0

[SDG5]
nombre=
valorGrupo=8
valorDecimal=1
valorHexadecimal=1
valorBinario=1
nombresBits=I_O1-I_O2-SEL2-R_W----
entradaBits=-------
estadoEntradaBits=0-0-0-0-0-0-0-0
secuencia=0
ordenSecuencia=0
valorInicio=0
valorFin=255
tiempoSecunecia=0
duracion=0
diferencial=0-0-0-0
frecuencias=0-0-0-0
conmutaBits=0-0-0-0-0-0-0-0
frecuBits=0-0-0-0-0-0-0-0

[SDG6]
nombre=
valorGrupo=0
valorDecimal=1
valorHexadecimal=1
valorBinario=1
nombresBits=-------
entradaBits=-------
estadoEntradaBits=0-0-0-0-0-0-0-0
secuencia=0
ordenSecuencia=0
valorInicio=0
valorFin=255
tiempoSecunecia=0
duracion=0
diferencial=0-0-0-0
frecuencias=0-0-0-0
conmutaBits=0-0-0-0-0-0-0-0
frecuBits=0-0-0-0-0-0-0-0

[SDG7]
nombre=
valorGrupo=0
valorDecimal=1
valorHexadecimal=1
valorBinario=1
nombresBits=-------
entradaBits=-------
estadoEntradaBits=0-0-0-0-0-0-0-0
secuencia=0
ordenSecuencia=0
valorInicio=0
valorFin=255
tiempoSecunecia=0
duracion=0
diferencial=0-0-0-0
frecuencias=0-0-0-0
conmutaBits=0-0-0-0-0-0-0-0
frecuBits=0-0-0-0-0-0-0-0

[EDG0]
nombre=
valorDecimal=1
valorHexadecimal=1
valorBinario=1
nombresBits=A1-A2-A3-A4-A5-A6-A7-A8
resistencia=1-1-1-1-1-1-1-1

[EDG1]
nombre=
valorDecimal=1
valorHexadecimal=1
valorBinario=1
nombresBits=C1-C2-C3-C4-C5-C6-C7-C8
resistencia=1-1-1-1-1-1-1-1

[EDG2]
nombre=
valorDecimal=1
valorHexadecimal=1
valorBinario=1
nombresBits=E_O-OUT1-OUT0-DIR-D24-D26-D212-D210
resistencia=1-1-1-1-1-1-1-1

[EDG3]
nombre=
valorDecimal=1
valorHexadecimal=1
valorBinario=1
nombresBits=-------
resistencia=1-1-1-1-1-1-1-1

[EDG4]
nombre=
valorDecimal=1
valorHexadecimal=1
valorBinario=1
nombresBits=-------
resistencia=1-1-1-1-1-1-1-1

[EDG5]
nombre=
valorDecimal=1
valorHexadecimal=1
valorBinario=1
nombresBits=-------
resistencia=1-1-1-1-1-1-1-1

[EDG6]
nombre=
valorDecimal=1
valorHexadecimal=1
valorBinario=1
nombresBits=-------
resistencia=1-1-1-1-1-1-1-1

[EDG7]
nombre=
valorDecimal=1
valorHexadecimal=1
valorBinario=1
nombresBits=-------
resistencia=1-1-1-1-1-1-1-1

[SAC1]
nombre=
estado=0

[SAC2]
nombre=
estado=0

[SAC3]
nombre=
estado=0

[SAC4]
nombre=
estado=0

[SAC5]
nombre=
estado=0

[SAC6]
nombre=
estado=0

[SAC7]
nombre=
estado=0

[SAC8]
nombre=
estado=0

[SAC9]
nombre=
estado=0

[SAC10]
nombre=
estado=0

[SAC11]
nombre=
estado=0

[SAC12]
nombre=
estado=0

[SAC13]
nombre=
estado=0

[SAC14]
nombre=
estado=0

[SAC15]
nombre=
estado=0
