# devg-coral.so parameters for tailoring to specific boards and display modes.
#
# See MB8629x Graphics Controller Specifications for further details.
#
# htp		Horizontal Total Pixels
# hdp		Horizontal Display Period
# hdb		Horizontal Display Boundary (for M & B layers) 
# hsp		Horizontal Synchronize pulse Position
# hsw		Horizontal Syncronize pulse Width
# vsw 		Vertical Synchronize pulse Width
# vtr		Vertical Total Rasters
# vsp		Vertical Synchronize pulse Position
# vdp		Vertical Display Period
# vidbase	Video Base Address (if PCI card, this value is ignored)
# regbase 	Register Base Address (if PCI card, this value is ignored)	
# vsize 	Amount of video memory
# irq		Interrupt number for InterruptAttach()
# mmr		Memory I/F Mode Register	
# dcm		Display Control Mode regsiter
# setup		Setup mode and memory (1 = setmode, 0 = keep current setup) 
# rsw		Register Location Switch (0 - registers at 0x1FC0000, 1 - registers at 0x3FC0000) *CORALP
# cge		Clock Select for Geometry Engine (166, 133, 100 Mhz)
# cot		Clock Select for others except geometry engine (133, 100 Mhz)
# type		chip type (0 - Coral Q, 1 - Coral B, 2 - Coral P)
# i2c		i2c base address (0 assumes no I2C)
# dlsize	memory size for 1 drawlist (in bytes)
# anti          global anti-aliasing : 0 = off 1 = on (currently only supports lines)
# phl           main display default layer: 0-5
# dlayers       SC0en & SC1en fields for Multi-Display Control register *Coral-PA only
# dmode         Dual Display mode (0 = single display, 1 = dual parallel mode, 2 = dual multiplexed mode) *Coral-PA only
#
# The driver will use the first un-commented entry.
# Note these are sample values and may need to be adjusted for your specific board
#

# 640x480 60 Hz (Coral-P PCI Reference Card) 
htp=800,hsp=656,hsw=96,hdp=640,hdb=640,vtr=525,vsp=490,vsw=2,vdp=480,vidbase=0,regbase=0,vsize=0x3fc0000,mmr=0x11d7fa13,dcm=0x700,setup=1,rsw=1,cge=166,cot=133,type=2,i2c=0x4a,dlsize=2048,anti=0,phl=2

# 640x480 60 Hz (Coral-B PCI Reference Card) 
#htp=800,hsp=656,hsw=96,hdp=640,hdb=640,vtr=525,vsp=490,vsw=2,vdp=480,vidbase=0,regbase=0,vsize=0x3fc0000,mmr=0x014eb813,dcm=0x700,setup=1,rsw=1,cge=100,cot=100,type=1,i2c=0x4a,dlsize=2048,anti=0,phl=2

# 320x240 60 Hz (Coral-P PCI Reference Card) 
#htp=424,hsp=324,hsw=48,hdp=320,hdb=320,vtr=263,vsp=245,vsw=2,vdp=240,vidbase=0,regbase=0,vsize=0x3fc0000,mmr=0x11d7fa13,dcm=0x1d00,setup=1,rsw=1,cge=166,cot=133,type=2,i2c=0x4a,dlsize=2048,anti=0,phl=2

# 400x240 60 Hz (Coral-P PCI Reference Card) 
#htp=530,hsp=470,hsw=50,hdp=400,hdb=400,vtr=263,vsp=241,vsw=2,vdp=240,vidbase=0,regbase=0,vsize=0x3fc0000,mmr=0x11d7fa13,dcm=0x1700,setup=1,rsw=1,cge=166,cot=133,type=2,i2c=0x4a,dlsize=2048,anti=0,phl=2

# 480x240 60 Hz (Coral-P PCI Reference Card)
#htp=636,hsp=520,hsw=72,hdp=480,hdb=480,vtr=263,vsp=245,vsw=2,vdp=240,vidbase=0,regbase=0,vsize=0x3fc0000,mmr=0x11d7fa13,dcm=0x1300,setup=1,rsw=1,cge=166,cot=133,type=2,i2c=0x4a,dlsize=2048,anti=0,phl=2

# 800x600 60 Hz (Coral-P PCI Reference Card) 
#htp=1056,hsp=840,hsw=128,hdp=800,hdb=800,vtr=628,vsp=601,vsw=4,vdp=600,vidbase=0,regbase=0,vsize=0x3fc0000,mmr=0x11d7fa13,dcm=0x400,setup=1,rsw=1,cge=166,cot=133,type=2,i2c=0x4a,dlsize=2048,anti=0,phl=2

# 1024x768 60 Hz (Coral-P PCI Reference Card) 
#htp=1344,hsp=1048,hsw=136,hdp=1024,hdb=1024,vtr=806,vsp=771,vsw=6,vdp=768,vidbase=0,regbase=0,vsize=0x3fc0000,mmr=0x11d7fa13,dcm=0x300,setup=1,rsw=1,cge=166,cot=133,type=2,i2c=0x4a,dlsize=2048,anti=0,phl=2

# 854x480 60 Hz (Coral-P PCI Reference Card) 
#htp=1062,hsp=900,hsw=104,hdp=854,hdb=854,vtr=525,vsp=490,vsw=3,vdp=480,vidbase=0,regbase=0,vsize=0x3fc0000,mmr=0x11d7fa13,dcm=0x500,setup=1,rsw=1,cge=166,cot=133,type=2,i2c=0x4a,dlsize=2048,anti=0,phl=2





