@VERSION 1

###############################################################################
# Se lanzan terminales para presentar las trazas
###############################################################################
@PROCESS @NAME="/usr/photon/bin/pterm" @NOPARAMS=1
@PROCESS @NAME="/usr/photon/bin/pterm" @NOPARAMS=1
@PROCESS @NAME="/usr/photon/bin/pterm" @NOPARAMS=1
@PROCESS @NAME="/usr/photon/bin/pterm" @NOPARAMS=1
@PROCESS @NAME="/usr/photon/bin/pterm" @NOPARAMS=1
@PROCESS @NAME="/usr/photon/bin/pterm" @NOPARAMS=1
@PROCESS @NAME="/usr/photon/bin/pterm" @NOPARAMS=1
@PROCESS @NAME="/usr/photon/bin/pterm" @NOPARAMS=1
@PROCESS @NAME="/usr/photon/bin/pterm" @NOPARAMS=1

###############################################################################
# Lanza el Servidor de Comunicaciones XCommSrv
###############################################################################
@PROCESS 
@NAME=$(INITIALIZER_COMMSRV)
@INIT_TM=80.0
INP_PIPE=mvb_pp 
#FR=15.625
HAS_MVB_BUS=1 
HAS_ETHPD_BUS=1
ETHPD_PERS_VARDB=/var/traintic/hist/ETHPDPerVarDB.bin 
ETHPD_PERS_FR=0.033333 
ETHPD_PERS_SIZE=10096 
ETHPD_NSDB_FILE=/home/traintic/config/ethpd.nsdb
WG_FR=0.1 
ETHPD_CONV_PERS=1 
ETHPD_COMM_ERROR=1 
ETHPD_DESC=/var/traintic/hist/ETHPDDescriptor.cfg 
ETHPD_MCAST_BASE_ADDR=239.33.0.0 
ETHPD_MCAST_BASE_MASK=255.255.0.0 
ETHPD_UNICAST_ADDR=10.216.26.91 
ETHPD_UDP_BASE=12047 
ETHPD_MCAST_CONFIG_MODE=0 
ETHPD_SEQUENCE_COUNTER=1 
ETHPD_TTL=64 
MVB_PERS_VARDB=/var/traintic/hist/MVBPerVarDB.bin
MVB_PERS_FR=0.033333
MVB_PERS_SIZE=10094
MVB_NSDB_FILE=/home/traintic/config/hmi$(CABINE_ID).nsdb
MVB_CONV_PERS=1
MVB_DESC=/var/traintic/hist/MVBDescriptor.cfg
#TM_VAR="PLC_TIME"
MVB_HW=$(MVB_HW_OPT)
MVB_MESSAGE_DATA=1
MVB_IPMVB_SRV=1
IPMVB_MAX_INP_MSG_SZ=2048
IPMVB_MAX_OUT_MSG_SZ=2048
MVB_CFTP=1
#CFTP_CLT=1
MVB_COMM_ERROR=80
TM_UTC=1

TERM=/dev/ttyp1 
V=2


###############################################################################
#Lanza el Servidor de Alarmas AlarmSrv
###############################################################################
@PROCESS 
@NAME=/home/traintic/bin/AlarmSrv 
@INIT_TM=25.0 
INP_PIPE=al_pp 
FR=15.625
WG_FR=0.1
AL_MAXCHECK=1000
AL_MAXNOT=100

TERM=/dev/ttyp2 
V=2

###############################################################################
#Lanza el Servidor del Historico CellLogSrv
###############################################################################
@PROCESS 
@NAME=/home/traintic/bin/CellLogSrv 
@INIT_TM=100.0
INP_PIPE=log_pp 
FR=15.625 
GES_PIPE=Ges
ALSRV_PIPE=al_pp
CNT_AREA=RECORD
LOG_AREA=RECORD 
LOCAL_LOG_SIZE=100000
LOCAL_LOG_NAME=/var/traintic/hist/LocalReg
ALARM_LOG_NAME=/var/traintic/hist/AlarmReg
ALARM_LOG_SIZE=6000000,0,1,2,3,4
COUNT_NM=/var/traintic/hist/CounterReg
CIBUF_SIZE=1000000
CIBUF_NM=cyclic 
CIBUF_FR=1
VAR_DESC_NM=/var/traintic/hist/vardesc.bin
WG_FR=7.8125
COUNT_GUARD_SZ=262144
REG_DEACT=1
REFRESH_INIT=1
MIN_REFRESH_TM=2147483640
FLUSH_TM=30
FLUSH="CCU_TrenOff"
KM="HOLA_MUNDO"
TFT_ON="TFT_ACTIVE"

TERM=/dev/ttyp3 
V=2

###############################################################################
# Lanza el proceso de Marshalling  MarshallVarDB
###############################################################################
@PROCESS 
@NAME=/home/traintic/bin/MarshallVarDB
@INIT_TM=1.0
VAR_FILE=/home/traintic/config/marshallVars_C$(CABINE_ID).csv
FR=7.8125
INP_PIPE=mvars_pp
TERM=/dev/ttyp4
V=2

###############################################################################
# Crea los enlaces simbolicos necesarios para la GuiAPP de los 
# ficheros que se crean en tiempo de ejecución
###############################################################################
@PROCESS 
@NAME=/home/traintic/etc/CreateLinks.ksh
TERM=/dev/ttyp5


###############################################################################
#Lanza la Aplicacion Grafica de MMEX
###############################################################################
@PROCESS 
@NAME=/home/traintic/bin/SMEX_Launcher.ksh  
TERM=/dev/ttyp6

###############################################################################
# Lanza la Aplicacion CduDB
###############################################################################
@PROCESS
@NAME=/home/traintic/bin/CduDB
CONFIG_FILE=/home/traintic/config/cduconfig.txt

TERM=/dev/ttyp7
-ENABLE_CONSOLE

###############################################################################
# Lanza servicios de alarmas Ethernet
###############################################################################
#@PROCESS
#@NAME=/home/traintic/bin/SMEXPosAlarmClt
#FR=0.25
#NSDB_FILE=/home/traintic/config/hmi$(CABINE_ID).nsdb
#GW_CFG_XML_FILE=/home/traintic/config/GWcfg.xml
#CABINEID=HMI$(CABINE_ID)
#SERVER_IP=10.216.26.91
#TERM=/dev/ttyp8
#V=2


###############################################################################
# Ordenes del proceso principal
###############################################################################
@MAIN  
@NAME=Initializer 
INP_PIPE=init_pp 
FR=0.5 
WG_FR=0.25 
MEM_SIZE=400000
V=3
TERM=/dev/ttyp0

###############################################################################
# Parametros del Iniciador de Procesos
###############################################################################
@INP_PIPE   INIT_PIPE=

###############################################################################
# Parametros Comunes a Todos los Procesos
###############################################################################
@COMMON  
WG_SVR=wg_srv 
WDOG=0
MEM=shmem 
VARDB=vardb 
VARDB_SIZE=1000000 
AL_FILE=/home/traintic/HMIData/HMIAlarms.xml
LOG_AR=RECORD 
VIS_AR=VIEW 
ACUS_AR=SOUND
