# devg-ravin.so parameters for tailoring to specific display modes.
# The driver will use the first un-commented entry.


# fpx		Display X resolution	
# fpy 		Display Y resolution	
# pixel_clock   Pixel clock setting for RAVINE register
# htotal
# hblankwidth
# hfrontporch
# hsyncwidth
# vtotal
# vblankwidth
# vfrontporch
# vsyncwidth
# digital  	set to 1 to use digital flatpanel
# analog	set to 1 to use analog 
# no_cursor	set to 1 to disable hw_cursor
# no_blit	set to 1 to disable offscreen blit accleration (free up layer)
# vidbase	video memory base address (must be set for non-pci systems)
# regbase	register base address (must be set for non-pci systems)
# memsize	amount of video memory  
# addr      I2C addr for Philips SAA711X		
# polysize	size of polygon buffer in kbytes
# clock		value for MemClock or SysClock
# sdram		value for MemSdramRegister
# refresh	value for MemRefreshCycle
# delay		value for MemClockDelay
# control	value for MemClockControl
# pci		set to 1 if PCI adapter and no PCI server is present (not needed for system with PCI server) 

# default 800x600 settings, PCI
#fpx=800,fpy=600,pixel_clock=0x00010901,htotal=1000,hblankwidth=180,hfrontporch=7,hsyncwidth=40,vtotal=619,vblankwidth=19,vfrontporch=2,vsyncwidth=12,digital=0,analog=1,no_cursor=0,no_blit=0,membase=0,memsize=0x1000000,addr=0x42,polysize=64,clock=0x10d00,sdram=0x10037,refresh=0x90102,control=0x344b5d01

# 640x480, PCI 
#fpx=640,fpy=480,pixel_clock=0x00010d03,htotal=800,hblankwidth=160,hfrontporch=16,hsyncwidth=34,vtotal=525,vblankwidth=45,vfrontporch=10,vsyncwidth=2,digital=0,analog=1,no_cursor=0,no_blit=0,membase=0,memsize=0x1000000,addr=0x42,polysize=64,clock=0x10d00,sdram=0x10037,refresh=0x90102,control=0x344b5d01

# default 800x600 settings NEC Eagle Board
#fpx=800,fpy=600,pixel_clock=0x00010901,htotal=1000,hblankwidth=180,hfrontporch=7,hsyncwidth=40,vtotal=619,vblankwidth=19,vfrontporch=2,vsyncwidth=12,digital=0,analog=1,no_cursor=0,no_blit=0,membase=0x0a000000,memsize=0x1000000,addr=0x42,polysize=64,clock=0x10d00,sdram=0x10037,refresh=0x90102,control=0x344b5d01

# 640x480, NEC Eagle board 
fpx=640,fpy=480,pixel_clock=0x00010d03,htotal=800,hblankwidth=160,hfrontporch=16,hsyncwidth=34,vtotal=525,vblankwidth=45,vfrontporch=10,vsyncwidth=2,digital=0,analog=1,no_cursor=0,no_blit=0,membase=0x0a000000,memsize=0x1000000,addr=0x42,polysize=64,clock=0x10d00,sdram=0x10037,refresh=0x90102,control=0x344b5d01
