#!/bin/sh
#
# /etc/system/sysinit
#
# This is the first script run by the system. It should
# start any systems services that would be in a monolithic
# *nix kernel.
#
# Author: Jon Bolado
# Company: Traintic
#
# Version: 1.1
# Date: 2013-09-11
#
#endif

# Change the path to get everything from the /bin and /sbin
export PATH=/sbin:/usr/sbin:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/opt/bin:/opt/sbin:/usr/photon/bin:/usr/photon/appbuilder:/opt/X11R6/bin:/usr/X11R6/bin
export LD_LIBRARY_PATH=/proc/boot:/lib:/usr/lib:/lib/dll:/opt/lib:/usr/photon/lib:/usr/photon/dll:/usr/local/lib:/opt/X11R6/lib:/usr/X11R6/lib

# These are integers
typeset -i VERBOSE SAFEMODE NO_ETC

# Don't pass on these envirnment vars...
typeset +x BOOTSRC SAFEMODE VERBOSE ROOTDEV NO_ETC

# Display some info if requested
if test 0$VERBOSE -ge 1; then
	print VSCRIPT=$VSCRIPT
	print BOOTSRC=$BOOTSRC
	print SAFEMODE=$SAFEMODE
	print VERBOSE=$VERBOSE
	print ROOTDEV=$ROOTDEV
	print NO_ETC=$NO_ETC
	if test 0$VERBOSE -ge 2; then
		set -x
	fi
	sleep 2
fi

# Start the slog resmgr
if ! test /dev/slog -ef /dev/slog; then
 	slogger
fi

# Start the pipe manager. It is needed for sub-shelling...
if ! test /dev/pipe -ef /dev/pipe; then
	if pipe; then
		typeset -i i=0
		while test $i -lt 60 -a ! /dev/pipe -ef /dev/pipe ; do
			sleep 1;
			let i=i+1;
		done
		unset i
	fi
	if ! test /dev/pipe -ef /dev/pipe; then
		print Unable to start pipe manager...
		exec sh
		exec fesh
	fi
fi

# Start the POSIX message queue/named semaphore manager
mqueue
 
# Mount extended partitions
if test -r /dev/hd0t78; then
	mount -r -t qnx4 /dev/hd0t78 /home/traintic
	print "...mounted QNX Partition /dev/hd0t78 read only at /home/traintic"
fi
if test -r /dev/hd0t79; then
	mount -w -t qnx4 /dev/hd0t79 /var/traintic
	print "...mounted QNX Partition /dev/hd0t79 read/write at /var/traintic"
fi

echo "Checking writable filesystem"
chkfsys -rP /dev/hd0t79

# Mount additional CF-Drives if user has enabled it.
if test -x /etc/system/config/usecfslot2; then
	print "Mounting additional CF-partitions..."
	if test -r /dev/hd1; then
	 	if test -r /dev/hd1t6; then
	 		mount -t dos /dev/hd1t6 /fs/hd1t6
			print "... mounted DOS Partition at /fs/hd1t6"
	 	fi
	 	if test -r /dev/hd1t11; then
	 		mount -t dos /dev/hd1t11 /fs/hd1t11
			print "...mounted DOS Partition at /fs/hd1t11"
	 	fi
	 	if test -r /dev/hd1t77; then
	 		mount -t qnx4 /dev/hd1t77 /fs/hd1t77	
			print "...mounted QNX Partition at /fs/hd1t77"
	 	fi
	 	if test -r /dev/hd1t78; then
	 		mount -t qnx4 /dev/hd1t78 /fs/hd1t78		
			print "...mounted QNX Partition at /fs/hd1t78"
	 	fi
	 	if test -r /dev/hd1t79; then
	 		mount -t qnx4 /dev/hd1t79 /fs/hd1t79		
			print "...mounted QNX Partition at /fs/hd1t79"
	 	fi
	 	if test -r /dev/hd1t131; then
	 		mount -t ext2 /dev/hd1t131 /fs/hd1t131
			print "...mounted Ext2 Partition at /fs/hd1t131"
	 	fi
	fi
fi

# Start the pseudo-tty manager (probably should let users fiddle the parm)
devc-pty -n 16

# Keyboard
io-hid -d ps2ser kbd:kbddev
devc-con-hid -n 2
waitfor /dev/con1

# Run Hardware detection script
if test -x /etc/system/sysdetect.ksh; then
	. /etc/system/sysdetect.ksh
fi

# By default the hostname will be the name of the hardware. This usually afect to the keyboard and touchscreen calibration config files.
#if test -x /tmp/target; then
  hostname $(cat /tmp/target)
  export HOSTNAME=$(hostname)
#fi

# Executes Hardware dependant script that loads drivers and exports needed variables.
. /etc/system/hw/$HW

# Creates the soft links to use the right XCommSrv and HMIBoot
ln -sP $INITIALIZER_COMMSRV /tmp/XCommSrv
ln -sP $INITIALIZER_HMIBOOT /tmp/HMIBoot

#tinit
on -t/dev/con1 sh
on -t/dev/con2 sh

# Run the system initialization script
if test -x /etc/rc.d/rc.cafinit; then
	. /etc/rc.d/rc.cafinit
fi
