# devg-orchid.so parameters for tailoring to specific boards and display modes.
#
# See MB86292 Graphics Controller Specifications for further details.
#
# htp		Horizontal Total Pixels
# hdp		Horizontal Display Period
# hdb		Horizontal Display Boundary (for M & B layers) 
# hsp		Horizontal Synchronize pulse Position
# hsw		Horizontal Syncronize pulse Width
# vsw 		Vertical Synchronize pulse Width
# vtr		Vertical Total Rasters
# vsp		Vertical Synchronize pulse Position
# vdp		Vertical Display Period
# vidbase	Video Base Address (if PCI card, this value is ignored)
# regbase 	Register Base Address (if PCI card, this value is ignored)	
# vsize 	Amount of video memory
# mmr		Memory I/F Mode Register	
# div		Pixel clock divider (for DCM regsiter) 
# setup		Setup mode and memory (1 = setmode, 0 = keep current setup) 
# irq		Devices Interrupt number
#
# The driver will use the first un-commented entry.
# Note these are sample values and may need to be adjusted for your specific board
#

# 640x480 60 Hz 50/50-split (PCI Reference Card) 
htp=800,hsp=656,hsw=96,hdp=640,hdb=320,vtr=525,vsp=490,vsw=2,vdp=480,vidbase=0,regbase=0,vsize=0x800000,mmr=0x009a984a,div=8,setup=1

# 320x240 60 Hz No-split (PCI Reference Card) 
#htp=424,hsp=324,hsw=48,hdp=320,hdb=320,vtr=263,vsp=245,vsw=2,vdp=240,vidbase=0,regbase=0,vsize=0x800000,mmr=0x009a984a,div=30,setup=1

# 400x240 60 Hz No-split (PCI Reference Card) 
#htp=530,hsp=470,hsw=50,hdp=400,hdb=400,vtr=263,vsp=241,vsw=2,vdp=240,vidbase=0,regbase=0,vsize=0x800000,mmr=0x009a984a,div=24,setup=1

# 480x240 60 Hz No-split (PCI Reference Card)
#htp=636,hsp=520,hsw=72,hdp=480,hdb=480,vtr=263,vsp=245,vsw=2,vdp=240,vidbase=0,regbase=0,vsize=0x800000,mmr=0x009a984a,div=20,setup=1

# 640x480 60 Hz No-split (PCI Reference Card) 
#htp=800,hsp=656,hsw=96,hdp=640,hdb=640,vtr=525,vsp=490,vsw=2,vdp=480,vidbase=0,regbase=0,vsize=0x800000,mmr=0x009a984a,div=8,setup=1

# 800x600 60 Hz No-split (PCI Reference Card) 
#htp=1056,hsp=840,hsw=128,hdp=800,hdb=800,vtr=628,vsp=601,vsw=4,vdp=600,vidbase=0,regbase=0,vsize=0x800000,mmr=0x009a984a,div=5,setup=1

# 1024x768 60 Hz No-split (PCI Reference Card) 
#htp=1344,hsp=1048,hsw=136,hdp=1024,hdb=1024,vtr=806,vsp=771,vsw=6,vdp=768,vidbase=0,regbase=0,vsize=0x800000,mmr=0x009a984a,div=3,setup=1

# 854x480 60 Hz No-split (PCI Reference Card) 
#htp=1062,hsp=900,hsw=104,hdp=854,hdb=854,vtr=525,vsp=490,vsw=3,vdp=480,vidbase=0,regbase=0,vsize=0x800000,mmr=0x009a984a,div=6,setup=1

